server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_music
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:postgresql://localhost:5432/test
  #    username: postgres
  #    password: 123456
  #    driver-class-name: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  web:
    resources:
      static-locations: file:src/main/resources/static # Locations of static resources.Defaults to classpath:[/META-INF/resources/, /resources/, /static/, /public/].

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  security:
    user:
      password: 123

  mail:
    host: smtp.qq.com
    username: 691523943@qq.com
    password: sdmmzwilojhobbjh
    protocol: smtp
    default-encoding: utf-8
    ssl:
      enabled: true
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      "[mail.smtp.port]": 465